services:
  - type: web
    name: wheel-horse-spin-mp-server
    runtime: node
    rootDir: multiplayer-race
    plan: free
    region: oregon
    autoDeploy: true
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: DATABASE_URL
        fromDatabase:
          name: wheel-horse-spin-db
          property: connectionString

databases:
  - name: wheel-horse-spin-db
    plan: free
    region: oregon
