services:
  - type: web
    name: wheel-horse-spin-mp-server
    runtime: node
    rootDir: multiplayer-race
    plan: free
    region: oregon
    autoDeploy: true
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080

  - type: web
    name: wheel-horse-spin-frontend
    runtime: static
    rootDir: .
    plan: free
    region: oregon
    autoDeploy: true
    buildCommand: ""
    staticPublishPath: .
    headers:
      - path: "**/*.js"
        name: Cache-Control
        value: no-cache
      - path: "**/*.css"
        name: Cache-Control
        value: no-cache
